### ISSUE TITLE
Support for specifying the activity ARN as a command line argument

### ISSUE THREAD

**Issue by elementonetech** [irothschild/stefuna#17]
Being able to specify the AWS Step Function Activity ARN on the command line would be greatly beneficial.  The existing override logic that exists for the worker definition would be a perfect pattern to follow here as well.

```python
    parser.add_argument('--activity-arn', dest='activity_arn', action='store', required=False,
                        help='Step Function Activity ARN, Overrides config setting.')
```
I'm happy to do the work and provide a PR.

~Drew

**Comment by irothschild** [comment]
Sounds good. I'd be happy to merge a PR.
