### ISSUE TITLE
Step function with multiple activity

### ISSUE THREAD

**Issue by berpweb** [irothschild/stefuna#19]
I am trying to understand this package in a better way. It works great for step function with a single activity. 

How it works if a step function is having more than one state and each state is having an activity?

```{
"Comment": "A Hello World example",
"StartAt": "One",
"States": {
    "One": {
      "Type": "Task",
      "Resource": "arn:aws:states:****:one",
      "Next": "Two"
    },
    "Two": {
      "Type": "Task",
      "Resource": "arn:aws:states:****:two",
      "End": true
    }
  }
}

#hello_worker.py
class One(Worker):
    def run_task(self, task_token, input_data):
        return {"message": "One"}

class Two(Worker):
    def run_task(self, task_token, input_data):
        return {"message": "Two"}
```

1) How can we execute stefuna now? Like this??
```
stefuna --worker=hello_worker.One --activity-arn=arn:aws:states:****:one
stefuna --worker=hello_worker.Two --activity-arn=arn:aws:states:****:two
```

If I execute like above am getting this error on the second command since the health check for both command listens to the same port. 

```
Traceback (most recent call last):
  File "/bin/stefuna", line 8, in <module>
    sys.exit(main())
  File "/lib/python3.6/site-packages/stefuna/stefuna.py", line 113, in main
    loglevel=loglevel_numeric)
  File "/lib/python3.6/site-packages/stefuna/server.py", line 86, in __init__
    self._create_healthcheck(healthcheck)
  File "/lib/python3.6/site-packages/stefuna/server.py", line 169, in _create_healthcheck
    self.healthcheck_http_server = HTTPServer(('', port), HealthcheckHTTPRequestHandler)
  File "lib/python3.6/socketserver.py", line 453, in __init__
    self.server_bind()
  File "lib/python3.6/http/server.py", line 136, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "lib/python3.6/socketserver.py", line 467, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
```

2) Do I need to create a separate python environment for each activity related code and change health check port?

3) Can you add this information to Readme?

**Comment by berpweb** [comment]
I think a simpler approach would be creating different config files for each activity worker and change the health check port on it.

Any better way to do it?

**Comment by irothschild** [comment]
I recommend using a different config file for each activity worker and changing the health check port in each. Alternatively, if you don't need the health check, you can set `healthcheck = None` in a shared config.

**Comment by berpweb** [comment]
I think it's better to use different config files and that resolves this question.
I am closing this issue. Thanks for your work with this framework and quick reply.
