### ISSUE TITLE
Can not pass dict as config

### ISSUE THREAD

**Issue by JoseAlban** [irothschild/stefuna#20]
If I run:
`pipenv run stefuna --config '{"a":1}'`

Then:
`Error loading config {"a":1}`

Because:
```
    if args.config:
        local_config = locate(args.config)
        if local_config is None:
            sys.stderr.write('Error loading config {0}\n'.format(args.config))
            sys.exit(-1)

```

locate() returns empty.

pydoc out of python 3.7

**Comment by irothschild** [comment]
Sorry, the docs are confusing. If been a while but I think by dict I mean a dict in a file. For example, If you have a file `myconfig.py`:

```
settings = { 'foo': 'bar' }
```

Then you can do:

```
stefuna --config myconfig.settings
```
